### ISSUE TITLE
Android build lib not found

### ISSUE THREAD

**Issue by tabago** [INDExOS/media-for-mobile#15]
samples folder inner libs folder not found 
OS X media_for_mobile inde sdk I would like to know how and where to download.

**Comment by hojatdelfan** [comment]
I have this problem too . 
somebody can help us ?

**Comment by pranav18** [comment]
I am also facing the same issue in android studio.
Where is the lib folder ?

**Comment by asuhov** [comment]
Media for Mobile has been open sourced (see it at https://github.com/INDExOS/media-for-mobile), now you can build the libraries by yourself.
