### ISSUE TITLE
Streamin live from camera

### ISSUE THREAD

**Issue by taprm** [INDExOS/media-for-mobile#19]
Hello!
I found post https://software.intel.com/en-us/articles/intel-inde-media-pack-for-android-tutorials-running-samples and I want send live stream from camera to Red5 server, but this sample is missing. Why? I found in repository sample, and add CameraStreamer Activity to menu. But this not works. 
    public Render createSink(StreamingParameters parameters, IProgressListener progressListener, ProgressTracker progressTracker) {
        // Was disabled publishing
        //return new MuxRender(new MediaStreamerInternal(parameters), progressListener, //progressTracker);
        throw new UnsupportedOperationException();
    }
How I can send stream from camera with Intel INDE?

Regards.

**Comment by silert** [comment]
Hello,
Sorry, we have excluded streaming functionality from the open source version of the Media for Mobile.

**Comment by asuhov** [comment]
Hello,
Sorry, we have excluded streaming functionality from the open source version of the Media for Mobile.
